### ISSUE TITLE
Crash on dedicated environments with item filter

### ISSUE THREAD

**Issue by Rearth** [Rearth/Oritech#146]
### Issue description

Log: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at rearth.oritech.client.ui.ItemFilterScreenHandler.method_7601(ItemFilterScreenHandler.java:60) ~[oritech-0.10.2.jar:?]
        at net.minecraft.class_1703.method_30010(class_1703.java:394) ~[server-intermediary.jar:?]
        at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12076(class_3244.java:1722) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_12191(class_2813.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_2813.method_11054(class_2813.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 21 more

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

todo

### Fabric API version

todo

### Oritech version

todo

### Other relevant versions

This is just a reminder for myself

**Comment by Rearth** [comment]
Should be fixed with 64eea2d68b06a07be48fac7cb486723ead3bef27
