### ISSUE TITLE
Exo Chestplate causes client to crash

### ISSUE THREAD

**Issue by kernohad** [Rearth/Oritech#29]
### Issue description

I made the Exo Chestplate and when I quipped it, it seemed to crash my client.

When I tried to join the server again, it kept saying "Internal Server Error". It was not until we manually removed the chestplate from my character that I could join the server again.

Here is the log
[19:34:16] [Server thread/INFO]: kernohd joined the game
[19:34:16] [Server thread/INFO]: Sending kernohd common config 'fallingtrees:fallingtrees_common'
[19:34:16] [Netty Epoll Server IO #0/INFO]: Receiving client config
[19:34:16] [Server thread/WARN]: Failed to handle packet for /68.9.193.136:52951
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:583) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:257) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:379) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at rearth.oritech.item.tools.armor.BackstorageExoArmorItem.method_7888(BackstorageExoArmorItem.java:31) ~[oritech-0.5.0.jar:?]
        at net.minecraft.class_1799.method_7917(class_1799.java:518) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:256) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:579) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2446) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:519) ~[server-intermediary.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at rearth.oritech.item.tools.armor.BackstorageExoArmorItem.method_7888(BackstorageExoArmorItem.java:31) ~[oritech-0.5.0.jar:?]
        at net.minecraft.class_1799.method_7917(class_1799.java:518) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:256) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:579) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2446) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:519) ~[server-intermediary.jar:?]
        ... 9 more
[19:34:16] [Server thread/INFO]: kernohd lost connection: Internal server error
[19:34:16] [Server thread/INFO]: kernohd left the game

FWIW: I crafted the item, then while it was in my active slot in my hotbar I right clicked. Not sure if equipping by dragging the item would work any better. 

### Steps to reproduce

1. Craft Exo Chestplate
2. Have Exo Chestplate in active slot of hot bar
3. Right click to equip chestplate

### Minecraft version

1.20.4 (No longer being developed)

### Fabric loader version

0.15.11

### Fabric API version

1.20.4

### Oritech version

0.5.0

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/kernohad/3de8a54511ab158a6a21d03ca1079772

**Comment by Rearth** [comment]
Hi, thanks for reporting this. I also ran into this issue when updating oritech to minecraft 1.21, and assumed it was the update that broke something. Since it only happens on servers I probably just never ran into it.
This is fixed in Oritech 0.6.0 onwards. Since you're still using the old version I assume minecraft 1.21 with more recent oritech versions is not an option for  you? Please let me know if using the never version is an option, otherwise I might (no promises though) backport this fix to the 1.20.4 version

**Comment by kernohad** [comment]
Glad to hear its resolved! We just spun this server up and chose the older version due to some of the other mods we want to use not being supported in 1.21 quite yet. So for the short term we will likely stay on 1.20.4

We would love the fix to be backported, but no pressure at all.

**Comment by Rearth** [comment]
Hi, so I just backported the fix, it's included in version 0.5.1:
https://github.com/Rearth/Oritech/releases/tag/v0.5.1%2B1.20.4
