### ISSUE TITLE
Log file error in some cases

### ISSUE THREAD

**Issue by Lolothepro** [Rearth/Oritech#48]
### Issue description

https://mclo.gs/6McW4qk

```
[14:27:07] [Server thread/ERROR]: Failed to save chunk 24,11
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10063()" because "this.areaMin" is null
	at rearth.oritech.block.base.entity.FrameInteractionBlockEntity.method_11007(FrameInteractionBlockEntity.java:268) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.base.entity.ItemEnergyFrameInteractionBlockEntity.method_11007(ItemEnergyFrameInteractionBlockEntity.java:94) ~[oritech-0.8.0.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:748) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_20605(class_3898.java:490) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17233(class_3898.java:441) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:314) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:27:07] [IO-Worker-1/INFO]: Saved details to /mnt/76561DD3561D94C9/MultiMC/instances/1.21(15)/.minecraft/debug/chunk-Culling-2024-08-01_14.27.07-server.txt
[14:27:07] [Server thread/ERROR]: Failed to save chunk 24,12
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10063()" because "this.areaMin" is null
	at rearth.oritech.block.base.entity.FrameInteractionBlockEntity.method_11007(FrameInteractionBlockEntity.java:268) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.base.entity.ItemEnergyFrameInteractionBlockEntity.method_11007(ItemEnergyFrameInteractionBlockEntity.java:94) ~[oritech-0.8.0.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:748) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_20605(class_3898.java:490) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17233(class_3898.java:441) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:314) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:27:08] [IO-Worker-1/INFO]: Saved details to /mnt/76561DD3561D94C9/MultiMC/instances/1.21(15)/.minecraft/debug/chunk-Culling-2024-08-01_14.27.08-server.txt
[14:27:08] [Server thread/ERROR]: Failed to save chunk 24,13
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10063()" because "this.areaMin" is null
	at rearth.oritech.block.base.entity.FrameInteractionBlockEntity.method_11007(FrameInteractionBlockEntity.java:268) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.base.entity.ItemEnergyFrameInteractionBlockEntity.method_11007(ItemEnergyFrameInteractionBlockEntity.java:94) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.base.entity.MultiblockFrameInteractionEntity.method_11007(MultiblockFrameInteractionEntity.java:43) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.entity.machines.interaction.DestroyerBlockEntity.method_11007(DestroyerBlockEntity.java:85) ~[oritech-0.8.0.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:748) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_20605(class_3898.java:490) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17233(class_3898.java:441) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:314) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:27:08] [IO-Worker-2/INFO]: Saved details to /mnt/76561DD3561D94C9/MultiMC/instances/1.21(15)/.minecraft/debug/chunk-Culling-2024-08-01_14.27.08-server.txt
[14:27:08] [Server thread/ERROR]: Failed to save chunk 24,14
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10063()" because "this.areaMin" is null
	at rearth.oritech.block.base.entity.FrameInteractionBlockEntity.method_11007(FrameInteractionBlockEntity.java:268) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.base.entity.ItemEnergyFrameInteractionBlockEntity.method_11007(ItemEnergyFrameInteractionBlockEntity.java:94) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.base.entity.MultiblockFrameInteractionEntity.method_11007(MultiblockFrameInteractionEntity.java:43) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.entity.machines.interaction.DestroyerBlockEntity.method_11007(DestroyerBlockEntity.java:85) ~[oritech-0.8.0.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:748) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_20605(class_3898.java:490) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17233(class_3898.java:441) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:314) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:27:08] [IO-Worker-6/INFO]: Saved details to /mnt/76561DD3561D94C9/MultiMC/instances/1.21(15)/.minecraft/debug/chunk-Culling-2024-08-01_14.27.08-server.txt
[14:27:09] [Server thread/ERROR]: Failed to save chunk 24,15
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10063()" because "this.areaMin" is null
	at rearth.oritech.block.base.entity.FrameInteractionBlockEntity.method_11007(FrameInteractionBlockEntity.java:268) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.base.entity.ItemEnergyFrameInteractionBlockEntity.method_11007(ItemEnergyFrameInteractionBlockEntity.java:94) ~[oritech-0.8.0.jar:?]
	at rearth.oritech.block.entity.machines.interaction.FertilizerBlockEntity.method_11007(FertilizerBlockEntity.java:68) ~[oritech-0.8.0.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:748) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_20605(class_3898.java:490) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17233(class_3898.java:441) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:314) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### Steps to reproduce

1. Generate a debug world

### Minecraft version

1.21 (Latest)

### Fabric loader version

0.16.0

### Fabric API version

0.100.8+1.21

### Oritech version

0.8.0

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

[chunk-Culling-2024-08-01_14.27.07-server.txt](https://github.com/user-attachments/files/16457385/chunk-Culling-2024-08-01_14.27.07-server.txt)
[chunk-Culling-2024-08-01_14.27.08-server.txt](https://github.com/user-attachments/files/16457386/chunk-Culling-2024-08-01_14.27.08-server.txt)
[chunk-Culling-2024-08-01_14.27.09-server.txt](https://github.com/user-attachments/files/16457387/chunk-Culling-2024-08-01_14.27.09-server.txt)
[chunk-Culling-2024-08-01_14.37.03-server.txt](https://github.com/user-attachments/files/16457388/chunk-Culling-2024-08-01_14.37.03-server.txt)
[chunk-Culling-2024-08-01_14.37.04-server.txt](https://github.com/user-attachments/files/16457389/chunk-Culling-2024-08-01_14.37.04-server.txt)
[chunk-Culling-2024-08-01_14.37.05-server.txt](https://github.com/user-attachments/files/16457390/chunk-Culling-2024-08-01_14.37.05-server.txt)

**Comment by Rearth** [comment]
Huh, that's an interesting error. Any change you could provide me some more information on how to reproduce the issue? Based on the logs, it seems like you have a fertilizer block somewhere. The block thinks it's connected to a machine frame, and so it tried to save the machine frame data. However, that data doesnt exist / is not set. Is there a block of that type, and is it connected to a machine frame? I don't understand how the block things it's connected, but then doesnt have any machine frame connection data
